name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Docker build
      run: docker build --tag karimmango/devops:v1 .
      
    - name: Docker login
      run: docker login --username karimmango --password ${DOCKER_PASSWORD}
      
    - name: Docker push
      run: docker push karimmango/devops:v1
